name: Deploy Personal Website

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy app
        run: |
          set -e

          echo "Deploy mulai..."

          cd /var/www/personal-website

          git pull origin main

          docker compose pull || true
          docker compose up -d --build

          echo "Deploy selesai"
