name: Deploy App

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no dockerserver@192.168.0.103 << 'EOF'
            set -e
            trap 'echo LOG ERROR DEPLOY: ' ERR

            cd /var/www/personal-website
            git pull origin main
            docker compose down || true
            docker compose up -d --build

            echo "DONE"
          EOF